### ISSUE TITLE
Why does .rosdistro for Rolling point to the `foxy-devel` branch?

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/realtime_tools#96]
I think this is causing a MoveIt package which depends on a new Rolling feature to fail.

https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml

```
  realtime_tools:
    doc:
      type: git
      url: https://github.com/ros-controls/realtime_tools.git
      version: foxy-devel
    release:
      tags:
        release: release/rolling/{package}/{version}
      url: https://github.com/ros2-gbp/realtime_tools-release.git
      version: 2.4.0-1
```
